### PR TITLE
More types

### PR DESCRIPTION
**Pull request by JonathanBout**
It may not be what the assignment asked, but I think it may be useful for some(?)

### CODE REVIEW

**Review by RFlintstone — APPROVED** [review]
LGTM 🚢

**Comment by JonathanBout** [comment]
SheepItShaunTheSheepGIF

**Comment by RFlintstone** [comment]
TitanicRoseGIF

**Comment by HJS-18** [comment]
LGTM 🚢

**Review by RFlintstone — APPROVED** [review]
JimHalpertFaceGIF

**Comment by Steven24K** [comment]
Intersting conversation guys

**Comment by RFlintstone** [comment]
Just doing code reviews :)

**Pull request merged**
