### PR TITLE
this is not a branch

### PR DESCRIPTION
**Pull request by RFlintstone**
- **Update .gitignore**
- **Delete henk/.idea directory**
- **Delete henk/index.js**
- **Library filter**

### CODE REVIEW

**Review by JonathanBout — APPROVED** [review]
lgtm

**Comment by RFlintstone** [comment]
> 

3dGIF

**Review by HJS-18 — APPROVED** [review]
lgtm

**Comment by HJS-18** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣶⣶⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠟⠛⢿⣿⡿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢀⡴⠚⢉⣷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣷⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⡞⠀⠀⠀⢿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⡟⠟⢡⢉⠣⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢧⠀⠀⠀⢸⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣣⠖⠱⠛⠙⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⢿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⢉⠟⢃⠞⠐⠋⢼⢹⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢰⠀⠀⠀⠸⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣯⡥⠴⣯⡀⠀⡐⢰⡵⣃⣮⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⡼⠀⠀⠀⠀⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⢯⡟⠀⠀⠈⠙⢶⡷⠂⠀⠿⣽⣿⣿⣿⠟⠋⠀⢠⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣠⠃⠀⠀⠀⠀⠈⢿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⠉⣇⠀⠀⠀⠀⠙⠳⠶⠤⠾⠟⠋⠀⠀⠀⣀⣾⣿⣿⣿⣷⣀⣀⣀⣀⠀⠀⠀⠀
⠀⠀⣀⣤⣒⣋⣀⣀⣀⣀⣀⣀⡀⠈⢻⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡤⠶⣿⣿⡀⢹⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣴⣿⣿⣿⢏⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶
⢀⡞⠁⠀⠀⠁⠀⠀⠈⠀⠀⠀⠹⡆⠀⣿⣤⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡀⠀⢿⣿⡇⠘⣿⣿⠟⢓⣒⡛⢷⣶⠾⢛⣛⠛⢿⣿⣿⡏⣸⣿⣿⡏⠀⢸⣿⣿⠟⠋⢉⠐
⠸⣷⣤⣤⣄⠀⠀⣠⠄⠀⡀⣤⣾⣿⣾⣿⣿⣿⣿⣶⣤⣀⡀⠀⠀⠀⠀⢀⣠⣴⡇⠀⠘⣿⣿⡄⢻⡇⠀⢿⣿⡿⢸⣿⣀⣿⣿⡷⠀⣿⡿⣰⣿⣿⣿⠀⢰⣿⣿⡏⠀⠀⢀⠀
⢀⡟⠉⠉⠙⠓⠚⠛⠓⠒⠚⠋⠉⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣠⣶⣿⢿⣧⣿⠀⠀⠘⢿⣿⣄⡿⠒⠒⠉⠀⠀⠀⠈⠉⠙⠲⢾⣿⣷⣿⣿⣿⠃⢀⣿⣿⣿⠀⠂⠄⠠⠀
⢸⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠊⠈⠻⣿⡷⠞⠋⠁⠀⠀⠀⠀⢾⣷⠀⠀⣴⠿⠆⠀⠀⠀⠀⠙⠿⣧⣴⣾⣿⣿⡿⣐⡂⠓⠟⠀
⠈⡿⠷⠶⢶⣶⣦⣤⣶⣾⣷⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⣼⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠋⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣷⣿⠇⠀⠁⠁
⠀⡇⠀⠀⠀⠀⠀⠈⠉⠉⠉⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⢳⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⢏⠀⠠⠄⠀
⠀⢿⣆⣀⡀⣀⠀⠀⠀⣠⣤⣠⣠⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⠀⣿⠲⣤⣀⣀⣀⣀⣀⣀⣀⣀⣀⡀⢀⣀⣀⣀⣀⣀⣀⣀⣀⣴⣦⣾⣿⣿⣿⣿⢇⠀⠁⠀⠀
⠀⢸⠀⠉⠉⠙⠛⠻⠿⠿⠿⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣿⣧⠻⣍⠛⡛⠿⡿⠛⢛⠛⠛⢛⡛⠛⠛⣿⣿⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⢩⡱⢀⠀⠁
⠀⠸⣄⠀⠀⠀⠀⠀⢀⠀⢀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣎⢧⠙⠲⢧⣀⣇⠀⢸⠀⠀⠐⠀⠀⠀⡇⠀⢸⣀⣸⠾⣛⣽⣿⡿⠋⢻⣿⣿⣤⠌⢰⠄
⠀⠀⠈⠉⠙⠓⠒⠛⢛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠙⠲⢤⣀⣀⠉⠉⠉⠓⠚⠓⠒⠊⠉⢉⣉⣤⣶⣿⣿⣿⣿⠃⠀⠸⣿⣿⣿⡀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣀⠀⠀⠉⠙⠛⠛⠿⢶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠀⠀⠀⡙⢿⣿⡧⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⣿⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣁⣀⣀⣠⣴⣾⡷⢠⡿⠁⠁⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠛⠻⠿⣿⠿⠿⠛⠛⠋⠁⠀⠀⠀⠈⠳⣄⠀⠉⠙⠛⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣴⠟⡡⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠓⠦⢤⣼⠋⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡼⠃⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⡴⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡞⠡⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⡤⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣰⡞⠳⣝⢦⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡟⠡⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⢋⣤⡀⣸⣾⣏⡳⣤⣰⣿⣿⣿⣿⣿⣿⣿⣿⡛⠉⠉⢹⣟⢧⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢴⢞⣿⡟⣱⣛⠞⣱⠟⢁⣼⠟⣦⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⣾⣯⣟⡀⢀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡻⢯⣀⣠⣴⠞⠁⠀⣉⡤⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣸⣿⣿⣧⣼⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡏⣓⣲⡺⣧⣶⠃⣸⣿⣋⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⢸⣿⡿⢿⠿⡿⠠⡄⠀

**Pull request merged**
